version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-morty}
      POSTGRES_PASSWORD: ${DB_USER:-password}
      POSTGRES_DB: morty
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
